In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


# Utilize o dataset zoo_2.csv e execute o algoritmo utilizando o método holdout, reservando apenas 20% dos dados para teste.

In [7]:
data = pd.read_csv('../../exercises/files-dataframes/zoo_2.csv')
zoo = pd.DataFrame(data)
zoo

hair  feathers   eggs   milk  airborne  aquatic  predator  toothed  \
0     True     False  False   True     False    False      True     True   
1     True     False  False   True     False    False     False     True   
2    False     False   True  False     False     True      True     True   
3     True     False  False   True     False    False      True     True   
4     True     False  False   True     False    False      True     True   
..     ...       ...    ...    ...       ...      ...       ...      ...   
96    True     False  False   True     False    False     False     True   
97    True     False   True  False      True    False     False    False   
98    True     False  False   True     False    False      True     True   
99   False     False   True  False     False    False     False    False   
100  False      True   True  False      True    False     False    False   

     backbone  breathes  venomous   fins  legs   tail  domestic  catsize  \
0        True      True     False  False     4  False     False     True   
1        True      True     False  False     4   True     False     True   
2        True     False     False   True     0   True     False    False   
3        True      True     False  False     4  False     False     True   
4        True      True     False  False     4   True     False     True   
..        ...       ...       ...    ...   ...    ...       ...      ...   
96       True      True     False  False     2   True     False     True   
97      False      True      True  False     6  False     False    False   
98       True      True     False  False     4   True     False     True   
99      False      True     False  False     0  False     False    False   
100      True      True     False  False     2   True     False    False   

             type  
0          mammal  
1          mammal  
2            fish  
3          mammal  
4          mammal  
..            ...  
96         mammal  
97         insect  
98         mammal  
99   invertebrate  
100          bird  

[101 rows x 17 columns]

In [9]:
X = zoo.drop(columns='type')  ## treinando dataset (sem a coluna de tipo)
y = zoo['type'] ## apenas a coluna de característicar (tipo)


In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) ## Dividindo os dados entre treino e teste, para utilização do método holdout que se baseia em usar 80% para treino e 20% para testes

In [ ]:
dtc = DecisionTreeClassifier() 

dtc.fit(X_train, y_train) ## Treinando o classificador 

DecisionTreeClassifier()

In [26]:
y_test_pred = dtc.predict(X_test) ## fazendo previsões nos conjunto de testes
y_train_pred = dtc.predict(X_train) 


# Gere a matriz de confusão para os datasets de treino e teste.


In [27]:
print("Matriz de Confusão:")
print(confusion_matrix(y_test, y_test_pred))

Matriz de Confusão:
[[ 0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0]
 [ 0  0  2  0  0  0  0]
 [ 0  0  0  3  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0 12  0]
 [ 1  0  0  0  0  0  0]]


# Compute as métricas (precision, recall e f1-score) para os conjutos de treino e teste

In [19]:
classification_report

<function sklearn.metrics._classification.classification_report(y_true, y_pred, *, labels=None, target_names=None, sample_weight=None, digits=2, output_dict=False, zero_division='warn')>

In [30]:
# A função "classification_report" computa as métricas (precision, recall e f1-score)

classification_report(y_train, y_train_pred)

'              precision    recall  f1-score   support\n\n   amphibian       1.00      1.00      1.00         4\n        bird       1.00      1.00      1.00        18\n        fish       1.00      1.00      1.00        11\n      insect       1.00      1.00      1.00         5\ninvertebrate       1.00      1.00      1.00         9\n      mammal       1.00      1.00      1.00        29\n     reptile       1.00      1.00      1.00         4\n\n    accuracy                           1.00        80\n   macro avg       1.00      1.00      1.00        80\nweighted avg       1.00      1.00      1.00        80\n'

In [31]:
accuracy_score(y_train, y_train_pred)


1.0

# Avalie e compare os resultados obtidos pelo dataset de treino e teste e identifique se houve overfitting, underfitting ou se o modelo induzido gerado é adequado para utilizar em dados não vistos.

In [ ]:
print("Conjunto de Treino:")
print("Acurácia:", accuracy_score(y_train, y_train_pred))
print("Relatório de Classificação (Treino):")
print(classification_report(y_train, y_train_pred))
print("Matriz de Confusão (Treino):")
print(confusion_matrix(y_train, y_train_pred))
# ----------------------------------------------------------------------- # 
print("Conjunto de Teste:")
print("Acurácia:", accuracy_score(y_test, y_test_pred))
print("Relatório de Classificação (Teste):")
print(classification_report(y_test, y_test_pred))
print("Matriz de Confusão (Teste):")
print(confusion_matrix(y_test, y_test_pred))

Conjunto de Treino:
Acurácia: 1.0
Relatório de Classificação (Treino):
              precision    recall  f1-score   support

   amphibian       1.00      1.00      1.00         4
        bird       1.00      1.00      1.00        18
        fish       1.00      1.00      1.00        11
      insect       1.00      1.00      1.00         5
invertebrate       1.00      1.00      1.00         9
      mammal       1.00      1.00      1.00        29
     reptile       1.00      1.00      1.00         4

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80

Matriz de Confusão (Treino):
[[ 4  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0]
 [ 0  0 11  0  0  0  0]
 [ 0  0  0  5  0  0  0]
 [ 0  0  0  0  9  0  0]
 [ 0  0  0  0  0 29  0]
 [ 0  0  0  0  0  0  4]]
Conjunto de Teste:
Acurácia: 0.9523809523809523
Relatório de Classificação (Teste):
              precision    recall  f1-score   supp

c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{

In [33]:
# ---> Overfitting : Pois o modelo tem um desempenho impecável nos treinos e no conjuto de testes ele não mantém o mesmo ritmo, até mesmo se mantendo em 0 em algumas ocasiôes

# Caso os resultados não estejam bons, altere os parâmetros do algoritmo para tentar melhorar o desempenho do modelo.

In [41]:
dtc = DecisionTreeClassifier(max_depth=5, random_state=42)

In [42]:
dtc

DecisionTreeClassifier(max_depth=5, random_state=42)

In [43]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [44]:
print("Conjunto de Treino:")
print("Acurácia:", accuracy_score(y_train, y_train_pred))
print("Relatório de Classificação (Treino):")
print(classification_report(y_train, y_train_pred))
print("Matriz de Confusão (Treino):")
print(confusion_matrix(y_train, y_train_pred))
# ----------------------------------------------------------------------- # 
print("Conjunto de Teste:")
print("Acurácia:", accuracy_score(y_test, y_test_pred))
print("Relatório de Classificação (Teste):")
print(classification_report(y_test, y_test_pred))
print("Matriz de Confusão (Teste):")
print(confusion_matrix(y_test, y_test_pred))

Conjunto de Treino:
Acurácia: 0.975
Relatório de Classificação (Treino):
              precision    recall  f1-score   support

   amphibian       1.00      1.00      1.00         4
        bird       1.00      1.00      1.00        18
        fish       1.00      1.00      1.00        11
      insect       1.00      0.60      0.75         5
invertebrate       0.82      1.00      0.90         9
      mammal       1.00      1.00      1.00        29
     reptile       1.00      1.00      1.00         4

    accuracy                           0.97        80
   macro avg       0.97      0.94      0.95        80
weighted avg       0.98      0.97      0.97        80

Matriz de Confusão (Treino):
[[ 4  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0]
 [ 0  0 11  0  0  0  0]
 [ 0  0  0  3  2  0  0]
 [ 0  0  0  0  9  0  0]
 [ 0  0  0  0  0 29  0]
 [ 0  0  0  0  0  0  4]]
Conjunto de Teste:
Acurácia: 0.9523809523809523
Relatório de Classificação (Teste):
              precision    recall  f1-score   su

c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{

In [45]:
# ---> Houve mudança nos resultados retornados, porém o retorno do conjunto de teste não se iguala com os resultados obtidos nos dados de treino 