In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


# Utilize o dataset zoo_2.csv e execute o algoritmo utilizando o método holdout, reservando apenas 20% dos dados para teste.

In [7]:
data = pd.read_csv('../../exercises/files-dataframes/zoo_2.csv')
zoo = pd.DataFrame(data)
zoo

hair  feathers   eggs   milk  airborne  aquatic  predator  toothed  \
0     True     False  False   True     False    False      True     True   
1     True     False  False   True     False    False     False     True   
2    False     False   True  False     False     True      True     True   
3     True     False  False   True     False    False      True     True   
4     True     False  False   True     False    False      True     True   
..     ...       ...    ...    ...       ...      ...       ...      ...   
96    True     False  False   True     False    False     False     True   
97    True     False   True  False      True    False     False    False   
98    True     False  False   True     False    False      True     True   
99   False     False   True  False     False    False     False    False   
100  False      True   True  False      True    False     False    False   

     backbone  breathes  venomous   fins  legs   tail  domestic  catsize  \
0        True      True     False  False     4  False     False     True   
1        True      True     False  False     4   True     False     True   
2        True     False     False   True     0   True     False    False   
3        True      True     False  False     4  False     False     True   
4        True      True     False  False     4   True     False     True   
..        ...       ...       ...    ...   ...    ...       ...      ...   
96       True      True     False  False     2   True     False     True   
97      False      True      True  False     6  False     False    False   
98       True      True     False  False     4   True     False     True   
99      False      True     False  False     0  False     False    False   
100      True      True     False  False     2   True     False    False   

             type  
0          mammal  
1          mammal  
2            fish  
3          mammal  
4          mammal  
..            ...  
96         mammal  
97         insect  
98         mammal  
99   invertebrate  
100          bird  

[101 rows x 17 columns]

In [9]:
X = zoo.drop(columns='type')  ## treinando dataset (sem a coluna de tipo)
y = zoo['type'] ## apenas a coluna de característicar (tipo)


In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) ## Dividindo os dados entre treino e teste, para utilização do método holdout que se baseia em usar 80% para treino e 20% para testes

In [11]:
dtc = DecisionTreeClassifier()

dtc.fit(X_train, y_train) ## Treinando o classificador 

DecisionTreeClassifier()

In [12]:
y_pred = dtc.predict(X_test) ## fazendo previsões no conjunto de testes

In [ ]:
X

hair  feathers   eggs   milk  airborne  aquatic  predator  toothed  \
89  False     False   True  False     False     True     False     True   
26  False     False   True  False     False     True      True     True   
42  False     False   True  False      True    False      True    False   
70   True     False  False   True     False    False     False     True   
15  False     False   True  False     False     True      True    False   
..    ...       ...    ...    ...       ...      ...       ...      ...   
60  False     False   True  False     False     True      True     True   
71  False      True   True  False     False    False      True    False   
14  False     False   True  False     False     True      True    False   
92  False     False   True  False     False     True      True     True   
51   True     False   True  False      True    False     False    False   

    backbone  breathes  venomous   fins  legs   tail  domestic  catsize  
89      True      True     False  False     4  False     False    False  
26      True      True      True  False     4  False     False    False  
42     False      True     False  False     6  False     False    False  
70      True      True     False  False     4   True      True     True  
15     False     False     False  False     6  False     False    False  
..       ...       ...       ...    ...   ...    ...       ...      ...  
60      True     False     False   True     0   True     False     True  
71      True      True     False  False     2   True     False     True  
14     False     False     False  False     4  False     False    False  
92      True     False     False   True     0   True     False     True  
51     False      True     False  False     6  False     False    False  

[80 rows x 16 columns]

# Gere a matriz de confusão para os datasets de treino e teste.


In [18]:
print("Matriz de Confusão:")
print(confusion_matrix(y_test, y_pred))

Matriz de Confusão:
[[ 0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0]
 [ 0  0  2  0  0  0  0]
 [ 0  0  0  3  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0 12  0]
 [ 1  0  0  0  0  0  0]]


# Compute as métricas (precision, recall e f1-score) para os conjutos de treino e teste